name: india_air_quality_json


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:
# on:
#   schedule:
#      - cron: '45 * * * *'  # Runs every 45th min

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install "snowflake-snowpark-python[pandas]"
          pip install requests pytz

      - name: Run ingestion script
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          DATA_GOV_API_KEY: ${{ secrets.DATA_GOV_API_KEY }}
        run: python ${{ github.workspace }}/ingest-api-data.py
